"""add usage session settlement fields

Revision ID: 12d3dd75c50e
Revises: 21934aa60528
Create Date: 2026-08-15 21:50:54.822469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d3dd75c50e'
down_revision: Union[str, Sequence[str], None] = '21934aa60528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_sessions', sa.Column('consumed_seconds', sa.BigInteger(), nullable=True))
    op.create_check_constraint('ck_usage_sessions_consumed_range', 'usage_sessions', '\n            consumed_seconds IS NULL\n            OR (\n                consumed_seconds >= 0\n                AND consumed_seconds <= authorized_seconds\n            )\n            ')
    op.create_check_constraint('ck_usage_sessions_lifecycle', 'usage_sessions', "\n            (\n                status = 'ACTIVE'\n                AND ended_at IS NULL\n                AND consumed_seconds IS NULL\n            )\n            OR\n            (\n                status = 'FINISHED'\n                AND ended_at IS NOT NULL\n                AND consumed_seconds IS NOT NULL\n            )\n            ")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_usage_sessions_lifecycle', 'usage_sessions', type_='check')
    op.drop_constraint('ck_usage_sessions_consumed_range', 'usage_sessions', type_='check')
    op.drop_column('usage_sessions', 'consumed_seconds')
    # ### end Alembic commands ###
