"""create usage sessions

Revision ID: 21934aa60528
Revises: 916300beefc8
Create Date: 2026-08-15 21:01:32.319310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21934aa60528'
down_revision: Union[str, Sequence[str], None] = '916300beefc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('authorized_seconds', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            status IN (\n                'ACTIVE',\n                'FINISHED'\n            )\n            ", name='ck_usage_sessions_status'),
    sa.CheckConstraint('authorized_seconds > 0', name='ck_usage_sessions_authorized_positive'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_usage_sessions_active_station', 'usage_sessions', ['station_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('uq_usage_sessions_active_user', 'usage_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_usage_sessions_active_user', table_name='usage_sessions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('uq_usage_sessions_active_station', table_name='usage_sessions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('usage_sessions')
    # ### end Alembic commands ###
