"""create time transactions ledger

Revision ID: afcda7962757
Revises: 8a4fc2593836
Create Date: 2026-08-15 13:01:22.819387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcda7962757'
down_revision: Union[str, Sequence[str], None] = '8a4fc2593836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('available_seconds_delta', sa.BigInteger(), nullable=False),
    sa.Column('reserved_seconds_delta', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            transaction_type IN (\n                'PURCHASE',\n                'SESSION_RESERVE',\n                'SESSION_USAGE',\n                'SESSION_RELEASE',\n                'BONUS',\n                'ADJUSTMENT',\n                'REFUND'\n            )\n            ", name='ck_time_transactions_type'),
    sa.CheckConstraint('\n            available_seconds_delta <> 0\n            OR reserved_seconds_delta <> 0\n            ', name='ck_time_transactions_non_zero_delta'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['time_wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_transactions_wallet_created_at', 'time_transactions', ['wallet_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_transactions_wallet_created_at', table_name='time_transactions')
    op.drop_table('time_transactions')
    # ### end Alembic commands ###
