"""create time sales

Revision ID: b488bfe49623
Revises: 5632ac4edd03
Create Date: 2026-08-17 23:30:51.292510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b488bfe49623'
down_revision: Union[str, Sequence[str], None] = '5632ac4edd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_type', sa.String(length=20), nullable=False),
    sa.Column('time_product_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('price_clp', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('time_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('usage_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                sale_type = 'REGISTERED'\n                AND customer_id IS NOT NULL\n                AND station_id IS NULL\n                AND time_transaction_id IS NOT NULL\n                AND usage_session_id IS NULL\n            )\n            OR\n            (\n                sale_type = 'GUEST'\n                AND customer_id IS NULL\n                AND station_id IS NOT NULL\n                AND time_transaction_id IS NULL\n                AND usage_session_id IS NOT NULL\n            )\n            ", name='ck_time_sales_result_by_type'),
    sa.CheckConstraint("\n            sale_type IN (\n                'REGISTERED',\n                'GUEST'\n            )\n            ", name='ck_time_sales_type'),
    sa.CheckConstraint('duration_seconds > 0', name='ck_time_sales_duration_positive'),
    sa.CheckConstraint('price_clp >= 0', name='ck_time_sales_price_non_negative'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['time_product_id'], ['time_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['time_transaction_id'], ['time_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usage_session_id'], ['usage_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time_transaction_id'),
    sa.UniqueConstraint('usage_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_sales')
    # ### end Alembic commands ###
